feat!: do not output files in editor
starikcetin/Eflatun.SceneReference pull request #94
Opened 2024-01-15 01:31 UTC by starikcetin

Closes #93

2024-01-15 16:43 UTC, starikcetin commented
> Hi, I see this feature uses EditorPrefs. I'm worried that this might cause some weird results when you switch projects. (Note that EditorPrefs is shared between all of your Unity projects). Make sure that the json is regenerated once the editor loads.
> 
> This will however still be problematic if for whatever reason someone decides to have 2 Unity projects open at the same time. A better solution might be to use EditorPrefs with a key that is unique per-project.

Don't bother reviewing right now. It's a draft, it'll change and get cleaned up.

2024-01-16 01:49 UTC, starikcetin commented
@CaseyHofland @mnemotic and everyone else interested, please review. I will merge in a week latest.

2024-01-16 17:44 UTC, mnemotic commented
I don't feel I'm qualified to review your code, but, like @CaseyHofland suggested, consider including `Application.productName` in the `EditorPrefs` key to reduce the chance of any collisions?

2024-01-16 20:50 UTC, starikcetin commented
> I don't feel I'm qualified to review your code, but, like @CaseyHofland suggested, consider including `Application.productName` in the `EditorPrefs` key to reduce the chance of any collisions?

We are not using EditorPrefs anymore, instead we are saving to UserSettings, which is already project specific.

2024-01-19 06:32 UTC, mnemotic commented
Ah. Then my comment doesn't apply. Show's exactly how qualified I am to review this. 😁

2024-01-19 07:23 UTC, starikcetin commented
> Ah. Then my comment doesn't apply. Shows exactly how qualified I am to review this. 😁

Don't be so hard on yourself :)

2024-01-20 00:00 UTC, starikcetin commented
@CaseyHofland Do you have any comments? I am going to merge it soon.

2024-01-20 15:38 UTC, CaseyHofland requested changes
Sorry, I kinda forgot about this! Usersettings is definitely the right solution, I don't use them enough myself!

There's one single change I would make because it's easy to do and would allow you to only do a minor increment.

2024-01-20 15:38 UTC, CaseyHofland commented on Eflatun.SceneReference/Packages/com.eflatun.scenereference/Editor/SceneDataMapsGenerator.cs
Replacing `Run()` with `Run(bool)` will not be backwards compatible, and if I'm right the rest of this commit is completely backwards compatible. It is a shame to leave low-hanging fruit so I suggest providing an overload that will fill out `Run(bool)` with the most expected behaviour, e.g.

```csharp
public static void Run() => Run(default);
```

If it really is not supposed to be called like this anymore, then do the above but give it an `[ObseleteAttribute]` to ease conversion.

2024-01-21 09:13 UTC, starikcetin commented on Eflatun.SceneReference/Packages/com.eflatun.scenereference/Editor/SceneDataMapsGenerator.cs
As for backwards compatibility: Behaviour is part of public API. We changed the behaviour, therefore this PR is breaking, no matter the API changes.

2024-01-21 11:11 UTC, CaseyHofland commented on Eflatun.SceneReference/Packages/com.eflatun.scenereference/Editor/SceneDataMapsGenerator.cs
Gotcha, well motivated. I still think letting the obsolete flag throw a warning is enough, although I have definitely worked in projects where a recompile would trigger 100+ warnings and the lead told me to “just clear it”; absolutely horrific.

2024-01-22 08:08 UTC, CaseyHofland approved these changes

2024-01-22 08:11 UTC, CaseyHofland commented on Eflatun.SceneReference/Packages/com.eflatun.scenereference/Editor/SceneDataMapsGenerator.cs
I don't think I have permission to resolve this conversation btw, may that be correct?

2024-01-22 18:04 UTC, merged

2024-01-22 18:05 UTC, starikcetin commented
Will be included in the next release.

2024-01-22 19:06 UTC, CaseyHofland commented
Chapeau

I have to personally thank you for the quick turnaround, when I asked for this feature I never expected it would get picked up so quickly. You’re an amazing creator you know that?

See you later space cowboy

2024-01-22 23:19 UTC, starikcetin commented
> Congrats!
> 
> I have to personally thank you for the quick turnaround, when I asked for this feature I never expected it would get picked up so quickly. You’re an amazing creator you know that?
> 
> See you space cowboy

It is very nice to hear kind words like this, thank you.